buy:
  success: "<color:#99ff94>✔</color> <white>Success <dark_gray>▪ <white>Bought <color:#99ff94>{amount}</color> charge(s) for <color:#99ff94>${price}</color>! You have <color:#99ff94>{charges}</color>/{max} remaining."
  insufficient-funds: "<gradient:#ff7817:#ffc46b>Insufficient funds! You need <color:#ffc885>${price}</color> but only have <color:#ffc885>${balance}</color>.</gradient>"
  max-exceeded: "<gradient:#ff7817:#ffc46b>Purchase would exceed maximum! You can only buy <color:#ffc885>{amount}</color> more.</gradient>"
  invalid-amount: "<gradient:#ff7817:#ffc46b>Invalid amount! Please specify a positive number.</gradient>"

toggle:
  "on": "<color:#99ff94>✔</color> <white>Success <dark_gray>▪ <white>Inventory protection <color:#99ff94>enabled</color>! You have <color:#99ff94>{charges}</color> charge(s) remaining."
  "off": "<color:#99ff94>✔</color> <white>Success <dark_gray>▪ <white>Inventory protection <color:#ff7817>disabled</color>! Your inventory will not be protected on death."

protection:
  triggered: "<gradient:#00ff00:#00aa00>Your inventory has been protected! <color:#99ff94>{charges}</color> charge(s) remaining.</gradient>"
  no-charges: "<gradient:#ff7817:#ffc46b>You died without any protection charges! Your inventory was not protected.</gradient>"
  disabled: "<gradient:#ff7817:#ffc46b>Protection is disabled. Use <color:#9ce8ff>/insureinv toggle</color> to enable.</gradient>"

info:
  header: "<gradient:#FFFFFF:#c9f505>━━━━━━━━━━ Player Info ━━━━━━━━━━</gradient>"
  player: "<dark_gray>▪ <white>Player: <color:#9ce8ff>{player}</color>"
  charges: "<dark_gray>▪ <white>Charges: <color:#9ce8ff>{charges}</color>/<color:#9ce8ff>{max}</color>"
  status: "<dark_gray>▪ <white>Status: {status}"
  total-purchases: "<dark_gray>▪ <white>Total Purchased: <color:#9ce8ff>{total_charges}</color>"
  usage-count: "<dark_gray>▪ <white>Times Protected: <color:#9ce8ff>{usage_count}</color>"
  footer: "<gradient:#FFFFFF:#c9f505>━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━</gradient>"

admin:
  set-success: "<color:#99ff94>✔</color> <white>Success <dark_gray>▪ <white>Set charges for <color:#9ce8ff>{player}</color> to <color:#9ce8ff>{amount}</color>."
  toggle-success: "<color:#99ff94>✔</color> <white>Success <dark_gray>▪ <white>Toggled protection to <color:#9ce8ff>{status}</color> for <color:#9ce8ff>{player}</color>."
  price-updated: "<color:#99ff94>✔</color> <white>Success <dark_gray>▪ <white>Price per charge updated to <color:#9ce8ff>${price}</color>."
  max-updated: "<color:#99ff94>✔</color> <white>Success <dark_gray>▪ <white>Max charges per player updated to <color:#9ce8ff>{max}</color>."

system:
  reload-complete: "<color:#99ff94>✔</color> <white>Success <dark_gray>▪ <white>Configuration reloaded!"
  reload-storage-changed: "<color:#99ff94>✔</color> <white>Success <dark_gray>▪ <white>Storage method changed to <color:#9ce8ff>{method}</color>. Data has been migrated."
  lang-reload-complete: "<color:#99ff94>✔</color> <white>Success <dark_gray>▪ <white>Language files reloaded!"
  lang-test: "<color:#99ff94>✔</color> <white>Language test <dark_gray>▪ <white>Your language: <color:#9ce8ff>{lang}</color>. This message is localized."
  lang-changed: "<color:#99ff94>✔</color> <white>Success <dark_gray>▪ <white>Language changed to <color:#9ce8ff>{lang}</color>."
  lang-current: "<color:#99ff94>✔</color> <white>Language <dark_gray>▪ <white>Current: <color:#9ce8ff>{lang}</color>. Available: <color:#9ce8ff>{available}</color>."
  lang-invalid: "<gradient:#ff7817:#ffc46b>Unknown language <color:#ffc885>{lang}</color>! Available: <color:#ffc885>{available}</color>.</gradient>"

error:
  no-permission: "<gradient:#ff7817:#ffc46b>You do not have permission to use this command!</gradient>"
  player-not-found: "<gradient:#ff7817:#ffc46b>Player <color:#ffc885>{player}</color> not found or has never joined.</gradient>"
  invalid-amount: "<gradient:#ff7817:#ffc46b>Invalid amount! Please specify a valid number.</gradient>"
  player-only: "<gradient:#ff7817:#ffc46b>This command can only be used by players!</gradient>"
  economy-unavailable: "<gradient:#ff7817:#ffc46b>Economy system is unavailable!</gradient>"
  transaction-failed: "<gradient:#ff7817:#ffc46b>Transaction failed! Please try again.</gradient>"

usage:
  buy: "<gradient:#ff7817:#ffc46b>Usage: <color:#9ce8ff>/insureinv buy <amount></color></gradient>"
  set: "<gradient:#ff7817:#ffc46b>Usage: <color:#9ce8ff>/insureinv set <player> <amount></color></gradient>"
  setprice: "<gradient:#ff7817:#ffc46b>Usage: <color:#9ce8ff>/insureinv setprice <amount></color></gradient>"
  setmax: "<gradient:#ff7817:#ffc46b>Usage: <color:#9ce8ff>/insureinv setmax <amount></color></gradient>"

help:
  header: "<gradient:#FFFFFF:#c9f505>━━━━━━━━━━━━ InsureInv Help ({page}/{total}) ━━━━━━━━━━━━</gradient>"
  buy: "<dark_gray>▪ <color:#9ce8ff>/insureinv buy <amount></color> <dark_gray>-</dark_gray> <white>Buy inventory protection charges</white>"
  toggle: "<dark_gray>▪ <color:#9ce8ff>/insureinv toggle [player]</color> <dark_gray>-</dark_gray> <white>Toggle inventory protection</white>"
  info: "<dark_gray>▪ <color:#9ce8ff>/insureinv info [player]</color> <dark_gray>-</dark_gray> <white>View charges and protection status</white>"
  set: "<dark_gray>▪ <color:#9ce8ff>/insureinv set <player> <amount></color> <dark_gray>-</dark_gray> <white>Set charges for player (Admin)</white>"
  setprice: "<dark_gray>▪ <color:#9ce8ff>/insureinv setprice <amount></color> <dark_gray>-</dark_gray> <white>Update price per charge (Admin)</white>"
  setmax: "<dark_gray>▪ <color:#9ce8ff>/insureinv setmax <amount></color> <dark_gray>-</dark_gray> <white>Update max charges (Admin)</white>"
  reload: "<dark_gray>▪ <color:#9ce8ff>/insureinv reload</color> <dark_gray>-</dark_gray> <white>Reload configuration (Admin)</white>"
  help: "<dark_gray>▪ <color:#9ce8ff>/insureinv help [page]</color> <dark_gray>-</dark_gray> <white>Display help information</white>"
  footer: "<gradient:#FFFFFF:#c9f505>━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━</gradient>"

status:
  enabled: "<color:#99ff94>Enabled</color>"
  disabled: "<color:#ff7817>Disabled</color>"
