name: '${name}'
version: '${version}-${gitCommit}'
main: dev.hytical.insureinv.InsureInvPlugin
api-version: '1.21'
folia-supported: true
authors: [ Hytical ]
website: https://qhuyy.tech/
description: Inventory protection plugin with economy integration

softdepend:
  - Vault
  - PlayerPoints
  - PlaceholderAPI

libraries:
  - org.jetbrains.kotlinx:kotlinx-coroutines-core:1.10.1
  - com.zaxxer:HikariCP:5.1.0

commands:
  insureinv:
    description: Main InsureInvPlugin command
    usage: /<command> <buy|toggle|info|set|setprice|setmax|reload|help> [args]
    aliases:
      - inv
      - hinv

permissions:
  insureinv.use:
    description: Allows using basic InsureInvPlugin commands
    default: true
  insureinv.admin:
    description: Allows using administrative InsureInvPlugin commands
    default: op
    children:
      insureinv.use: true